name: cart_quest
description: "Capstone project"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4

#packages
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12



#icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

#state_management:
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.11.0

#product specific
firebase_core: ^3.11.0

#packages-end

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #local assets
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
  #local fonts


