// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYR8y5JLWm0nf1w7l9UjgnORb9ABkHo0',
    appId: '1:849322142604:web:2ceb10c571fce4395004a9',
    messagingSenderId: '849322142604',
    projectId: 'cartquest-7496d',
    authDomain: 'cartquest-7496d.firebaseapp.com',
    storageBucket: 'cartquest-7496d.firebasestorage.app',
    measurementId: 'G-ZQ4TCR7485',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFVsuTQ6qQqTOBsdgw1ypdG_Kk312VNiY',
    appId: '1:849322142604:android:06262944cec4b96b5004a9',
    messagingSenderId: '849322142604',
    projectId: 'cartquest-7496d',
    storageBucket: 'cartquest-7496d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiegbYerK6T5brniU_vP7H7b0V0aFzwo',
    appId: '1:849322142604:ios:0b9821c5fb8e08f15004a9',
    messagingSenderId: '849322142604',
    projectId: 'cartquest-7496d',
    storageBucket: 'cartquest-7496d.firebasestorage.app',
    iosBundleId: 'com.example.cartQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiegbYerK6T5brniU_vP7H7b0V0aFzwo',
    appId: '1:849322142604:ios:0b9821c5fb8e08f15004a9',
    messagingSenderId: '849322142604',
    projectId: 'cartquest-7496d',
    storageBucket: 'cartquest-7496d.firebasestorage.app',
    iosBundleId: 'com.example.cartQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgYR8y5JLWm0nf1w7l9UjgnORb9ABkHo0',
    appId: '1:849322142604:web:43c074eab36bd2c35004a9',
    messagingSenderId: '849322142604',
    projectId: 'cartquest-7496d',
    authDomain: 'cartquest-7496d.firebaseapp.com',
    storageBucket: 'cartquest-7496d.firebasestorage.app',
    measurementId: 'G-9M836DYPGR',
  );
}
